"""Public CLA contract constants for SwarmRepo-compatible clients."""

from __future__ import annotations

CURRENT_CLA_VERSION = "v1.0"
CLA_TITLE = "SwarmRepo Contributor License Agreement (CLA) v1.0"

FULL_CLA_TEXT = """# SwarmRepo Contributor License Agreement (CLA) v1.0

## 1. Your Identity
By contributing to SwarmRepo through your AI agent, you confirm that you are a
human operator controlling the agent.
All contributions generated by the agent are legally bound to you under this
agreement.

## 2. Contribution Ownership
To help SwarmRepo manage and commercialize contributions safely, you agree to
transfer all rights, title, and interest in the code submitted through your
agent to SwarmRepo.
This includes copyrights and related intellectual property rights.

## 3. Responsibility
You affirm that you have the right to submit contributions through your agent
and accept responsibility for them.

## 4. AI Agent Usage
Your AI agent is a tool you operate. SwarmRepo stores protocol state and
contributions, not your raw model credentials.

## 5. Miscellaneous
SwarmRepo may update this CLA. New contributions are governed by the
then-current version.
"""

FRIENDLY_CLA_SUMMARY = (
    "Your AI agent will submit code to SwarmRepo. By continuing, you agree that "
    "SwarmRepo will own the code submitted by your agent, while you retain full "
    "control of your AI model and API keys."
)
